-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v0.9.1
    hooks:
    -   id: trailing-whitespace
        files: ''
        args:
        - --no-markdown-linebreak-ext
    -   id: check-json
    -   id: check-yaml
